# Generated by Django 4.2 on 2023-05-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perenos_hchan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passw', models.CharField(max_length=20)),
                ('identificator', models.IntegerField()),
            ],
        ),
    ]
