# Generated by Django 4.2 on 2023-05-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perenos_hchan', '0003_manga_postavte5_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Manga',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Postavte5',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Root',
        ),
    ]
